import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "../styles/globals.css";
import "../../public/assets/css/style.css";
import { Providers } from "./providers";
import NextTopLoader from "nextjs-toploader";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AlgoTicket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <NextTopLoader zIndex={999999}></NextTopLoader> */}
        {/* <body className={inter.className}> */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
